grades: main.c store.h store.c compute.h compute.c
	gcc main.c store.c compute.c -o student_grades

chemistry: main.c store.h store.c compute.h compute.c
	gcc -DSUBJECT=chemistry main.c store.c compute.c -o student_grades

english: main.c store.h store.c compute.h compute.c
	gcc -DSUBJECT=english main.c store.c compute.c -o student_grades

math: main.c store.h store.c compute.h compute.c
	gcc -DSUBJECT=math main.c store.c compute.c -o student_grades
